# Generated by Django 3.0.6 on 2020-11-03 04:23

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Coupon Code')),
                ('isUsed', models.BooleanField(default=False, verbose_name='Is Used')),
                ('expiresOn', models.DateTimeField(verbose_name='Expires On')),
            ],
            options={
                'verbose_name': 'CouponCode',
                'verbose_name_plural': 'CouponCodes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User Id')),
                ('section_name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('oid', models.IntegerField(verbose_name='Object Id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('twelve_hours', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=5, verbose_name='Twelve hours')),
                ('one_hour', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=5, verbose_name='One hour')),
                ('is_subscribed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=5, verbose_name='Subscription')),
                ('subscription_date', models.DateField(blank=True, null=True, verbose_name='Subscription Date')),
                ('subscription_duration', models.IntegerField(blank=True, null=True, verbose_name='Subscription Duration')),
                ('date_registered', models.DateTimeField(auto_now=True, verbose_name='Date Registered')),
                ('disabled', models.CharField(default='N', max_length=50, verbose_name='Notification')),
                ('email_notification', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=5, verbose_name='Email Notification')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
