# Generated by Django 3.0.6 on 2020-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='Is Subscribed'),
        ),
    ]
