# Generated by Django 3.0.6 on 2020-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disabled_notification',
            field=models.CharField(default='N', max_length=50, verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_subscribed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=5, verbose_name='Subscription'),
        ),
    ]
