# Generated by Django 3.0.6 on 2020-11-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201104_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Subscription ID'),
        ),
    ]
