# Generated by Django 3.0.6 on 2020-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201104_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Coupon Code'),
        ),
    ]
