# Generated by Django 3.0.6 on 2020-11-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bounds',
            field=models.CharField(max_length=100, verbose_name='Bounds'),
        ),
    ]
